#!/bin/sh /etc/rc.common

START=60

lease_file=/var/dhclient6.leases
config_file=/etc/dhclient6.conf
pid_file=/var/run/dhclient6.pid
script_file=/usr/sbin/dhclient-script

start() {
	/usr/sbin/dhclient -nw -6 -P -N -cf $config_file -lf $lease_file -pf $pid_file -sf $script_file eth0.1 eth0.2
	
	if [ $? -ne 0 ]; then
		return 1
	fi
}

stop() {
	if [ ! -e $pid_file ]; then
		return 1
	fi

	kill -9 `cat $pid_file`

	if [ $? -ne 0 ]; then
		return 1
	fi
	
	rm $pid_file
}
